Makefile.inc: fix systemd path
opensvc/multipath-tools pull request #52
Opened 2022-10-27 09:50 UTC by eworm-de

If `prefix` was set to `/usr`, then files would install inside `/usr/usr/`.

2022-10-27 10:10 UTC, mwilck requested changes

2022-10-27 10:10 UTC, mwilck commented on Makefile.inc
> +	SYSTEMDPATH=lib
no, this is incorrect. We should rather set SYSTEMDPATH where we set the other paths.

2022-10-27 10:13 UTC, mwilck commented on Makefile.inc
> +	SYSTEMDPATH=lib
Sorry, this wasn't "incorrect". But still I'd like to do this differently.

For the time being, you can just build with `make SYSTEMDPATH=/lib`, no?

2022-10-27 10:41 UTC, eworm-de commented
Pushed an update... Something like this?

2022-10-27 13:16 UTC, mwilck commented
> Pushed an update... Something like this?

yes, much better. But I think we should embed this in a larger `Makefile.inc` cleanup.

2022-11-02 13:53 UTC, mwilck commented
@eworm-de, could you please test with #53?

2022-12-19 09:36 UTC, closed without merging